// src/components/OpenSource.svelte
<script>
  import { onMount } from 'svelte';
  import { fetchPRsClient } from '../lib/github';

  export let grouped = [];
  export let totalPRs = 0;
  export let username = 'AlexanderDev2004';

  let liveGrouped = grouped;
  let liveTotal = totalPRs;
  let refreshing = false;
  let expandedRepo = '';

  $: projects = liveGrouped.length;

  onMount(async () => {
    // Build-time data renders instantly (SEO + no layout shift).
    // Then refresh client-side so the section stays "dynamically generated"
    // like elianiva.com without needing SSR.
    try {
      refreshing = true;
      const fresh = await fetchPRsClient(username);
      if (fresh && fresh.totalPRs > 0) {
        // Only swap when the fresh payload is non-empty to avoid
        // flashing an empty state on rate-limit.
        liveGrouped = fresh.grouped;
        liveTotal = fresh.totalPRs;
      }
    } finally {
      refreshing = false;
    }
  });

  function toggleRepo(fullName) {
    expandedRepo = expandedRepo === fullName ? '' : fullName;
  }

  function formatDate(value) {
    try {
      return new Date(value).toLocaleDateString('en-US', {
        day: 'numeric',
        month: 'short',
        year: 'numeric',
      });
    } catch {
      return value;
    }
  }
</script>

<div class="space-y-3">
  <p class="text-xs sm:text-sm muted-text leading-relaxed">
    Merged pull requests in other people&rsquo;s projects over the last year, most recent first.
    {#if refreshing}<span class="opacity-60">· refreshing…</span>{/if}
  </p>

  {#if liveGrouped.length > 0}
    <div class="space-y-2">
      {#each liveGrouped as group (group.repository.full_name)}
        <div class="surface-item rounded-lg overflow-hidden reveal">
          <button
            type="button"
            class="w-full text-left p-3 sm:p-4 flex justify-between items-start gap-3 pressable"
            onclick={() => toggleRepo(group.repository.full_name)}
            aria-expanded={expandedRepo === group.repository.full_name}
          >
            <div class="flex-1 min-w-0">
              <div class="flex items-baseline gap-2 flex-wrap">
                <a
                  href={group.repository.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  class="text-sm sm:text-base font-bold accent-link truncate"
                  onclick={(e) => e.stopPropagation()}
                >
                  {group.repository.full_name}
                </a>
                <span class="pill-chip text-[11px] font-semibold px-2 py-0.5">
                  ★ {group.repository.stargazerCount}
                </span>
                <span class="pill-chip text-[11px] font-semibold px-2 py-0.5">
                  {group.mergedCount} merged
                </span>
              </div>
              <p class="text-[11px] sm:text-xs muted-text mt-1">
                last merged · {formatDate(group.lastMergedAt)}
              </p>
            </div>
            <svg
              class="w-4 h-4 mt-1 shrink-0 transition-transform duration-300 {expandedRepo === group.repository.full_name ? 'rotate-180' : ''}"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              aria-hidden="true"
            >
              <polyline points="6 9 12 15 18 9"></polyline>
            </svg>
          </button>

          {#if expandedRepo === group.repository.full_name}
            <ul class="px-3 sm:px-4 pb-3 space-y-2 expand-reveal" style="border-top: 1px solid var(--surface-border);">
              {#each group.prs as pr (pr.id)}
                <li class="pt-2">
                  <a
                    href={pr.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    class="group/pr flex items-start gap-2 text-xs sm:text-sm primary-text hover:underline"
                  >
                    <iconify-icon icon="mdi:source-pull" width="16" height="16" class="mt-0.5 shrink-0"></iconify-icon>
                    <span class="flex-1 min-w-0">
                      <span class="font-medium">#{pr.number} {pr.title}</span>
                      <span class="block muted-text text-[11px] sm:text-xs mt-0.5">
                        merged · {formatDate(pr.merged_at)}
                      </span>
                    </span>
                  </a>
                </li>
              {/each}
            </ul>
          {/if}
        </div>
      {/each}
    </div>
    <p class="text-[11px] sm:text-xs muted-text font-mono pt-1">
      {liveTotal} merged pull request{liveTotal === 1 ? '' : 's'} across {projects} project{projects === 1 ? '' : 's'}
      · <a href={`https://github.com/pulls?q=author%3A${username}+is%3Amerged`} target="_blank" rel="noopener noreferrer" class="accent-link">view on GitHub</a>
    </p>
  {:else}
    <div class="text-center py-8 surface-item rounded-lg">
      <p class="muted-text text-sm">No merged pull requests from the last year to show.</p>
      <p class="muted-text text-xs mt-1 opacity-70">Data refreshes automatically every 24h.</p>
    </div>
  {/if}
</div>

// src/components/OpenSource.tsx
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import {
  EXCLUDED_REPOS,
  fetchPRsClient,
  GITHUB_USERNAME,
  type GitHubPRData,
  type RepositoryPRGroup,
} from '../lib/github'
import githubSnapshot from '../data/github.json'

function formatStars(count: number): string {
  if (count >= 1000) {
    const k = count / 1000
    return `${k >= 10 || count % 1000 === 0 ? Math.round(k) : k.toFixed(1)}k`
  }
  return String(count)
}

function monthYear(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', { month: 'short', year: 'numeric' })
}

function shortDate(iso: string): string {
  const d = new Date(iso)
  const dd = String(d.getDate()).padStart(2, '0')
  const mm = String(d.getMonth() + 1).padStart(2, '0')
  return `${dd}/${mm}/${d.getFullYear()}`
}

function RepoGroup({ group }: { group: RepositoryPRGroup }) {
  const [open, setOpen] = useState(true)

  const toggle = () => setOpen((v) => !v)

  return (
    <section className="os-group">
      <div
        className="os-repo"
        role="button"
        tabIndex={0}
        aria-expanded={open}
        aria-label={`${open ? 'Collapse' : 'Expand'} ${group.repository.full_name} pull requests`}
        onClick={toggle}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault()
            toggle()
          }
        }}
      >
        <iconify-icon className="os-caret" icon="mdi:chevron-down" />
        <a
          className="os-repo-name"
          href={group.repository.url}
          target="_blank"
          rel="noopener noreferrer"
          onClick={(e) => e.stopPropagation()}
          onKeyDown={(e) => e.stopPropagation()}
        >
          {group.repository.full_name}
          <iconify-icon icon="mdi:arrow-top-right" />
        </a>
        <div className="os-repo-meta">
          <span title={`${group.mergedCount} merged PRs`}>
            <iconify-icon icon="mdi:source-pull" />
            {group.mergedCount}
          </span>
          <span title={`${group.repository.stargazerCount} stars`}>
            <iconify-icon icon="mdi:star-outline" />
            {formatStars(group.repository.stargazerCount)}
          </span>
        </div>
        <span className="os-last">last merged {monthYear(group.lastMergedAt)}</span>
      </div>

      {open && (
        <ul className="os-prs">
          {group.prs.map((pr) => (
            <li key={pr.number}>
              <div className="os-line">
                <a
                  className="os-pr-title"
                  href={pr.url}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  {pr.title}
                </a>
                <span className="os-diff">
                  {pr.additions !== undefined && <span className="add">+{pr.additions}</span>}
                  {pr.deletions !== undefined && <span className="del">-{pr.deletions}</span>}
                </span>
              </div>
              <div className="os-line os-line-sub">
                <span className="os-pr-sub">
                  #{pr.number} • merged {shortDate(pr.merged_at)}
                </span>
                {pr.changedFiles !== undefined && (
                  <span className="os-files">
                    {pr.changedFiles} {pr.changedFiles === 1 ? 'file' : 'files'}
                  </span>
                )}
              </div>
            </li>
          ))}
        </ul>
      )}
    </section>
  )
}

/** Open Source Contributions card (elianiva-style PR list, approved reference). */
export function OpenSource() {
  // The snapshot is a build artifact produced by scripts/fetch-github.mjs;
  // its JSON-inferred types are structurally compatible but looser, so cast.
  const initial = githubSnapshot.prs as unknown as GitHubPRData

  const { data } = useQuery<GitHubPRData | null>({
    queryKey: ['github-prs', GITHUB_USERNAME],
    // Silent client refresh — build-time snapshot renders instantly,
    // fresh PR data swaps in only when non-empty (anti-flicker).
    queryFn: () => fetchPRsClient(GITHUB_USERNAME),
    initialData: initial,
    staleTime: 24 * 60 * 60 * 1000,
  })

  const grouped = (data?.grouped ?? []).filter(
    (group) => !EXCLUDED_REPOS.has(group.repository.full_name),
  )
  const totalPRs = grouped.reduce((sum, g) => sum + g.mergedCount, 0)

  return (
    <div className="block os">
      <div className="os-head">
        <span className="os-tick" />
        <h3>Open Source Contributions</h3>
      </div>
      <p className="os-sub">
        Merged pull requests in other people&rsquo;s projects over the last year, most
        recent first.
      </p>

      {grouped.length > 0 ? (
        <div className="os-card">
          {grouped.map((group) => (
            <RepoGroup key={group.repository.full_name} group={group} />
          ))}
          <div className="os-foot">
            {totalPRs} merged pull request{totalPRs === 1 ? '' : 's'} across{' '}
            {grouped.length} project{grouped.length === 1 ? '' : 's'}
          </div>
        </div>
      ) : (
        <div className="skeleton" style={{ height: 120, maxWidth: 560 }} />
      )}
    </div>
  )
}
